export const APPIUM_DEFAULT_PORT = 4723;
export const APPIUM_STARTUP_TIMEOUT_MS = 30_000;
export const APPIUM_HEALTH_CHECK_INTERVAL_MS = 500;
export const WEBDRIVER_REQUEST_TIMEOUT_MS = 10_000;
export const TAP_PAUSE_DURATION_MS = 100;
