export const EXPECT_LIVE_VIEW_URL_ENV_NAME = "EXPECT_LIVE_VIEW_URL";
export const EXPECT_REPLAY_OUTPUT_ENV_NAME = "EXPECT_REPLAY_OUTPUT_PATH";
export const EXPECT_NO_COOKIES_ENV_NAME = "EXPECT_NO_COOKIES";
